/* 符号配置中心：新增条目时放入对应 section 的 items 数组。 */
window.SYMBOL_SECTIONS=[
  {id:"greek-lower",title:"希腊字母 · 小写",subtitle:"Greek lowercase",items:[
    {symbol:"α",name:"Alpha",cn:"阿尔法",markdown:"$\\alpha$"},{symbol:"β",name:"Beta",cn:"贝塔",markdown:"$\\beta$"},{symbol:"γ",name:"Gamma",cn:"伽马",markdown:"$\\gamma$"},{symbol:"δ",name:"Delta",cn:"德尔塔／变化量",markdown:"$\\delta$"},{symbol:"ε",name:"Epsilon",cn:"艾普西隆",markdown:"$\\varepsilon$"},{symbol:"ζ",name:"Zeta",cn:"泽塔",markdown:"$\\zeta$"},{symbol:"η",name:"Eta",cn:"伊塔",markdown:"$\\eta$"},{symbol:"θ",name:"Theta",cn:"西塔",markdown:"$\\theta$"},{symbol:"ι",name:"Iota",cn:"约塔",markdown:"$\\iota$"},{symbol:"κ",name:"Kappa",cn:"卡帕",markdown:"$\\kappa$"},{symbol:"λ",name:"Lambda",cn:"拉姆达",markdown:"$\\lambda$"},{symbol:"μ",name:"Mu",cn:"缪／均值",markdown:"$\\mu$"},{symbol:"ν",name:"Nu",cn:"纽",markdown:"$\\nu$"},{symbol:"ξ",name:"Xi",cn:"克西",markdown:"$\\xi$"},{symbol:"ο",name:"Omicron",cn:"奥密克戎",markdown:"$o$",note:"标准 LaTeX 通常使用拉丁小写 o"},{symbol:"π",name:"Pi",cn:"派／圆周率",markdown:"$\\pi$"},{symbol:"ρ",name:"Rho",cn:"柔／相关系数",markdown:"$\\rho$"},{symbol:"σ",name:"Sigma",cn:"西格玛／标准差",markdown:"$\\sigma$"},{symbol:"τ",name:"Tau",cn:"陶",markdown:"$\\tau$"},{symbol:"υ",name:"Upsilon",cn:"宇普西隆",markdown:"$\\upsilon$"},{symbol:"φ",name:"Phi",cn:"斐",markdown:"$\\varphi$"},{symbol:"χ",name:"Chi",cn:"卡方常用字母",markdown:"$\\chi$"},{symbol:"ψ",name:"Psi",cn:"普西",markdown:"$\\psi$"},{symbol:"ω",name:"Omega",cn:"欧米伽",markdown:"$\\omega$"}
  ]},
  {id:"greek-upper",title:"希腊字母 · 大写",subtitle:"Greek uppercase",items:[
    {symbol:"Α",name:"Alpha",cn:"大写阿尔法",markdown:"$A$"},{symbol:"Β",name:"Beta",cn:"大写贝塔",markdown:"$B$"},{symbol:"Γ",name:"Gamma",cn:"大写伽马",markdown:"$\\Gamma$"},{symbol:"Δ",name:"Delta",cn:"大写德尔塔／变化",markdown:"$\\Delta$"},{symbol:"Ε",name:"Epsilon",cn:"大写艾普西隆",markdown:"$E$"},{symbol:"Ζ",name:"Zeta",cn:"大写泽塔",markdown:"$Z$"},{symbol:"Η",name:"Eta",cn:"大写伊塔",markdown:"$H$"},{symbol:"Θ",name:"Theta",cn:"大写西塔",markdown:"$\\Theta$"},{symbol:"Ι",name:"Iota",cn:"大写约塔",markdown:"$I$"},{symbol:"Κ",name:"Kappa",cn:"大写卡帕",markdown:"$K$"},{symbol:"Λ",name:"Lambda",cn:"大写拉姆达",markdown:"$\\Lambda$"},{symbol:"Μ",name:"Mu",cn:"大写缪",markdown:"$M$"},{symbol:"Ν",name:"Nu",cn:"大写纽",markdown:"$N$"},{symbol:"Ξ",name:"Xi",cn:"大写克西",markdown:"$\\Xi$"},{symbol:"Ο",name:"Omicron",cn:"大写奥密克戎",markdown:"$O$"},{symbol:"Π",name:"Pi",cn:"大写派／连乘",markdown:"$\\Pi$"},{symbol:"Ρ",name:"Rho",cn:"大写柔",markdown:"$P$"},{symbol:"Σ",name:"Sigma",cn:"大写西格玛／求和",markdown:"$\\Sigma$"},{symbol:"Τ",name:"Tau",cn:"大写陶",markdown:"$T$"},{symbol:"Υ",name:"Upsilon",cn:"大写宇普西隆",markdown:"$\\Upsilon$"},{symbol:"Φ",name:"Phi",cn:"大写斐",markdown:"$\\Phi$"},{symbol:"Χ",name:"Chi",cn:"大写希",markdown:"$X$"},{symbol:"Ψ",name:"Psi",cn:"大写普西",markdown:"$\\Psi$"},{symbol:"Ω",name:"Omega",cn:"大写欧米伽",markdown:"$\\Omega$"}
  ]},
  {id:"change",title:"变化与三角符号",subtitle:"Change & triangle",items:[
    {symbol:"∆",name:"Increment",cn:"增量符号",markdown:"$\\Delta$"},{symbol:"Δ",name:"Delta",cn:"有限变化量",markdown:"$\\Delta$"},{symbol:"δ",name:"Small delta",cn:"微小变化量",markdown:"$\\delta$"},{symbol:"∇",name:"Nabla",cn:"梯度／倒三角算子",markdown:"$\\nabla$"},{symbol:"△",name:"White triangle",cn:"空心上三角",markdown:"$\\triangle$"},{symbol:"▽",name:"White down triangle",cn:"空心下三角",markdown:"$\\triangledown$"},{symbol:"▲",name:"Black up triangle",cn:"实心上三角",markdown:"$\\blacktriangle$"},{symbol:"▼",name:"Black down triangle",cn:"实心下三角",markdown:"$\\blacktriangledown$"},{symbol:"◁",name:"Left triangle",cn:"空心左三角",markdown:"$\\triangleleft$"},{symbol:"▷",name:"Right triangle",cn:"空心右三角",markdown:"$\\triangleright$"}
  ]},
  {id:"calculus",title:"微积分与运算",subtitle:"Calculus & operators",items:[
    {symbol:"∂",name:"Partial",cn:"偏导数",markdown:"$\\partial$"},{symbol:"∑",name:"Summation",cn:"求和",markdown:"$\\sum$"},{symbol:"∏",name:"Product",cn:"连乘",markdown:"$\\prod$"},{symbol:"∫",name:"Integral",cn:"积分",markdown:"$\\int$"},{symbol:"∬",name:"Double integral",cn:"二重积分",markdown:"$\\iint$"},{symbol:"∭",name:"Triple integral",cn:"三重积分",markdown:"$\\iiint$"},{symbol:"√",name:"Square root",cn:"平方根",markdown:"$\\sqrt{x}$"},{symbol:"∞",name:"Infinity",cn:"无穷",markdown:"$\\infty$"},{symbol:"±",name:"Plus-minus",cn:"正负",markdown:"$\\pm$"},{symbol:"∓",name:"Minus-plus",cn:"负正",markdown:"$\\mp$"},{symbol:"×",name:"Times",cn:"乘号",markdown:"$\\times$"},{symbol:"÷",name:"Division",cn:"除号",markdown:"$\\div$"},{symbol:"·",name:"Centered dot",cn:"点乘",markdown:"$\\cdot$"},{symbol:"∘",name:"Composition",cn:"复合运算",markdown:"$\\circ$"},{symbol:"°",name:"Degree",cn:"度",markdown:"$^\\circ$"}
  ]},
  {id:"relations",title:"关系与集合",subtitle:"Relations & sets",items:[
    {symbol:"=",name:"Equal",cn:"等于",markdown:"$=$"},{symbol:"≠",name:"Not equal",cn:"不等于",markdown:"$\\ne$"},{symbol:"≈",name:"Approximately",cn:"约等于",markdown:"$\\approx$"},{symbol:"≡",name:"Equivalent",cn:"恒等／等价",markdown:"$\\equiv$"},{symbol:"≤",name:"Less or equal",cn:"小于等于",markdown:"$\\leq$"},{symbol:"≥",name:"Greater or equal",cn:"大于等于",markdown:"$\\geq$"},{symbol:"≪",name:"Much less",cn:"远小于",markdown:"$\\ll$"},{symbol:"≫",name:"Much greater",cn:"远大于",markdown:"$\\gg$"},{symbol:"∝",name:"Proportional",cn:"正比于",markdown:"$\\propto$"},{symbol:"∈",name:"Element of",cn:"属于",markdown:"$\\in$"},{symbol:"∉",name:"Not element of",cn:"不属于",markdown:"$\\notin$"},{symbol:"⊂",name:"Subset",cn:"真子集",markdown:"$\\subset$"},{symbol:"⊆",name:"Subset or equal",cn:"子集",markdown:"$\\subseteq$"},{symbol:"∪",name:"Union",cn:"并集",markdown:"$\\cup$"},{symbol:"∩",name:"Intersection",cn:"交集",markdown:"$\\cap$"},{symbol:"∀",name:"For all",cn:"任意／全称量词",markdown:"$\\forall$"},{symbol:"∃",name:"Exists",cn:"存在",markdown:"$\\exists$"},{symbol:"∅",name:"Empty set",cn:"空集",markdown:"$\\varnothing$"}
  ]},
  {id:"arrows",title:"箭头与方向",subtitle:"Arrows & direction",items:[
    {symbol:"→",name:"Right arrow",cn:"右箭头／趋向",markdown:"$\\rightarrow$"},{symbol:"←",name:"Left arrow",cn:"左箭头",markdown:"$\\leftarrow$"},{symbol:"↔",name:"Left-right arrow",cn:"双向箭头",markdown:"$\\leftrightarrow$"},{symbol:"⇒",name:"Implies",cn:"推出",markdown:"$\\Rightarrow$"},{symbol:"⇐",name:"Implied by",cn:"由此推出",markdown:"$\\Leftarrow$"},{symbol:"⇔",name:"If and only if",cn:"当且仅当",markdown:"$\\Leftrightarrow$"},{symbol:"↑",name:"Up arrow",cn:"上升",markdown:"$\\uparrow$"},{symbol:"↓",name:"Down arrow",cn:"下降",markdown:"$\\downarrow$"},{symbol:"↗",name:"North-east arrow",cn:"上升趋势",markdown:"$\\nearrow$"},{symbol:"↘",name:"South-east arrow",cn:"下降趋势",markdown:"$\\searrow$"},{symbol:"↦",name:"Maps to",cn:"映射到",markdown:"$\\mapsto$"}
  ]}
];
