const taxonId=document.body.dataset.taxon;
const data=window.SERPENT_SPECIES?.[taxonId];
const photos=window.SERPENT_PHOTOS?.[taxonId]||[];
const logs=[...(window.SERPENT_LOGS?.[taxonId]||[])].sort((a,b)=>b.date.localeCompare(a.date));
let photoIndex=0;
const el=id=>document.getElementById(id);
const nodeMap=new Map(),parentMap=new Map();
function indexTree(node,parent=null){nodeMap.set(node.id,node);if(parent)parentMap.set(node.id,parent.id);(node.children||[]).forEach(child=>indexTree(child,node))}indexTree(window.SERPENT_TREE);
function lineageFor(id){const path=[];let current=id;while(current){path.unshift(nodeMap.get(current));current=parentMap.get(current)}return path}
function projectPoint([lat,lng]){return [((lng+180)/360)*1000,((90-lat)/180)*500]}
function worldMap(distribution){const grid=[100,200,300,400].map(y=>`<line x1="0" y1="${y}" x2="1000" y2="${y}"/>`).join("")+[167,333,500,667,833].map(x=>`<line x1="${x}" y1="0" x2="${x}" y2="500"/>`).join("");const ranges=(distribution?.polygons||[]).map(p=>`<polygon class="range-shape" points="${p.map(projectPoint).map(x=>x.join(",")).join(" ")}"/>`).join("");const map=window.SERPENT_WORLD_MAP;return `<svg data-outline-nodes="${map.nodeCount}" viewBox="0 0 1000 500" role="img" aria-label="${distribution.label}"><g class="graticule">${grid}</g><g class="land">${map.landSvg()}</g><g>${ranges}</g></svg>`}
function renderPhotos(){const empty=el("photo-empty"),shell=el("photo-shell");empty.hidden=photos.length>0;shell.hidden=!photos.length;if(!photos.length)return;photoIndex=Math.max(0,Math.min(photoIndex,photos.length-1));el("photo-stage").innerHTML=photos.map((photo,index)=>{const d=index-photoIndex,l=Math.max(-2,Math.min(2,d)),distance=Math.abs(d);return `<figure class="photo-card" style="z-index:${10-distance};opacity:${distance>2?0:.5};filter:blur(${distance?3:0}px);transform:translate(${l*48-50}%,-50%) scale(${distance?0.8:1})"><img src="../../${photo.src}" alt="${photo.alt||photo.title}"></figure>`}).join("");el("photo-title").textContent=photos[photoIndex].title;el("photo-progress").textContent=`${photoIndex+1} / ${photos.length}`;el("prev").disabled=photoIndex===0;el("next").disabled=photoIndex===photos.length-1}
function movePhoto(step){const next=photoIndex+step;if(next>=0&&next<photos.length){photoIndex=next;renderPhotos()}}
function render(){if(!data){document.body.innerHTML='<main class="species-main"><div class="empty">找不到这个物种的档案配置。</div></main>';return}const node=nodeMap.get(taxonId);document.title=`${node.name} · 蛇谱`;el("name").textContent=node.name;el("latin").textContent=node.latin;el("english-name").textContent=data.englishName||"Species profile";el("summary").textContent=data.summary;el("lineage").innerHTML=lineageFor(taxonId).map(item=>`<span>${item.name}</span>`).join("");el("facts").innerHTML=Object.entries(data.profile||{}).map(([label,value])=>`<div class="fact"><span>${label}</span><strong>${value}</strong></div>`).join("");el("identification").innerHTML=(data.identification||[]).map(x=>`<li>${x}</li>`).join("");el("similar").innerHTML=(data.similar||[]).map(x=>`<li>${x}</li>`).join("");el("map").innerHTML=worldMap(data.distribution);el("map-note").innerHTML=`<strong>${data.distribution.label}</strong> · ${data.distribution.note}`;el("log-list").innerHTML=logs.length?logs.map(log=>`<a class="log-item" href="../../${log.url}"><time>${log.date}</time><div><h3>${log.title}</h3><p>${log.summary||"打开日志阅读全文"}</p></div><span>↗</span></a>`).join(""):'<div class="empty">还没有观察或学习日志。</div>';el("log-folder").textContent=`taxa/${taxonId}/logs/日期-标题/index.html`;el("sources").innerHTML=(data.sources||[]).map(source=>`<li><a href="${source.url}" target="_blank" rel="noreferrer">${source.label}</a></li>`).join("");renderPhotos()}
document.querySelector(".tabs").addEventListener("click",event=>{const button=event.target.closest("[data-view]");if(!button)return;document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x===button));el("photos-view").hidden=button.dataset.view!=="photos";el("map-view").hidden=button.dataset.view!=="map"});el("prev").addEventListener("click",()=>movePhoto(-1));el("next").addEventListener("click",()=>movePhoto(1));el("year").textContent=new Date().getFullYear();render();
